
version: '2.1'

services:

  users_db:
    container_name: usersdb
    build: ./app/db
    ports:
      - 5435:5432
    env_file: db_cred.env
    healthcheck:
      test: exit 0

  users:
    container_name: users_service
    build: .
    ports:
      - 5000
    env_file: 
      - web_prod.env
      - db_prod.env
    depends_on:
      users_db:
        condition: service_healthy
    links:
      - users_db
    command: gunicorn -b 0.0.0.0:5000 app.main:app

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users:
        condition: service_started
    links:
      - users
        
