version: '2.1'

services:

  users_db:
    container_name: usersdb
    image: users_db_img
    build: ./server/db
    ports:
      - 5435:5432
    env_file: db_cred.env
    healthcheck:
      test: exit 0

  users:
    container_name: users_service
    build: .
    image: users_img
    volumes:
      - ".:/usr/src/app" # HOST:CONTAINER dir map mounting
    ports:
      - 5500:5000
    env_file: 
      - web.env
      - db.env
    depends_on:
      users_db:
        condition: service_healthy
    links:
      - users_db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      users:
        condition: service_started
    links:
      - users
        
